apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: orderflow
spec:
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: 633212682415.dkr.ecr.ap-south-1.amazonaws.com/orderflow-order-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: orderflow-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: orderflow-config
                  key: DB_PORT
            - name: DB_NAME
              value: orderflow_order
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: orderflow-secrets
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: orderflow-secrets
                  key: POSTGRES_PASSWORD
            - name: INVENTORY_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: orderflow-config
                  key: INVENTORY_SERVICE_URL
            - name: INVENTORY_SERVICE_TIMEOUT_MS
              valueFrom:
                configMapKeyRef:
                  name: orderflow-config
                  key: INVENTORY_SERVICE_TIMEOUT_MS
            - name: FULFILLMENT_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: orderflow-config
                  key: FULFILLMENT_SERVICE_URL
            - name: FULFILLMENT_SERVICE_TIMEOUT_MS
              valueFrom:
                configMapKeyRef:
                  name: orderflow-config
                  key: FULFILLMENT_SERVICE_TIMEOUT_MS
            - name: INCIDENT_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: orderflow-config
                  key: INCIDENT_SERVICE_URL
            - name: INCIDENT_SERVICE_TIMEOUT_MS
              valueFrom:
                configMapKeyRef:
                  name: orderflow-config
                  key: INCIDENT_SERVICE_TIMEOUT_MS
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: orderflow-secrets
                  key: JWT_SECRET
            - name: JWT_EXPIRATION_MS
              valueFrom:
                secretKeyRef:
                  name: orderflow-secrets
                  key: JWT_EXPIRATION_MS
            - name: ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: orderflow-secrets
                  key: ADMIN_USERNAME
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: orderflow-secrets
                  key: ADMIN_PASSWORD
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 35
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: orderflow
spec:
  selector:
    app: order-service
  ports:
    - port: 8081
      targetPort: 8081
